name: untitled4
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

  #--------PACKAGES--------#
dependencies:
  flutter:
    sdk: flutter

  # Utility packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.2.0
  lottie: ^3.1.0
  shimmer: ^3.0.0
  image_picker: ^1.1.1
  url_launcher: ^6.2.6
  connectivity_plus: ^6.0.3
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.9
  emoji_picker_flutter: ^2.1.1
  flutter_notification_channel: ^3.1.0
  gallery_saver_updated: ^3.0.0
  cached_network_image: ^3.3.1
  #googleapis_auth_io: ^2.1.0
  flutter_slidable: ^3.1.0


  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  #Stat Management
  get: ^4.6.6
  get_storage: ^2.1.1


  #Firebase
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.3
  google_sign_in: ^6.2.1
  firebase_storage: ^11.7.4
  firebase_messaging: ^14.9.1

  # Product Specific
  #--------./ PACKAGES END--------#

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0



flutter:


  uses-material-design: true

  #--------LOCAL ASSETS--------#
  assets:
    - assets/logos/
    - assets/logos/
    - assets/icons/brands/
    - assets/images/user/
    - assets/images/chat/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/sliders/
    - assets/images/orders_devices/

  #--------LOCAL fonts--------#
  fonts:
    - family: 'Poppins'
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600

