// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm1-0gpeMPXsXPMKRGhXUUtx9j8TuD3a4',
    appId: '1:1004613572381:web:620899ee18e06c204933f4',
    messagingSenderId: '1004613572381',
    projectId: 'repair-c9eba',
    authDomain: 'repair-c9eba.firebaseapp.com',
    storageBucket: 'repair-c9eba.appspot.com',
    measurementId: 'G-FGPTMXP2ZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAdEDrpzlbk9blzWds5AvZT3DsR4cg5fk',
    appId: '1:1004613572381:android:f35c75d2e195c6854933f4',
    messagingSenderId: '1004613572381',
    projectId: 'repair-c9eba',
    storageBucket: 'repair-c9eba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMufkcLr2now7UgN5hy6_9_e8RUBOQXTI',
    appId: '1:1004613572381:ios:d4530ca02581d9474933f4',
    messagingSenderId: '1004613572381',
    projectId: 'repair-c9eba',
    storageBucket: 'repair-c9eba.appspot.com',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMufkcLr2now7UgN5hy6_9_e8RUBOQXTI',
    appId: '1:1004613572381:ios:d4530ca02581d9474933f4',
    messagingSenderId: '1004613572381',
    projectId: 'repair-c9eba',
    storageBucket: 'repair-c9eba.appspot.com',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm1-0gpeMPXsXPMKRGhXUUtx9j8TuD3a4',
    appId: '1:1004613572381:web:600de0f7931cdee44933f4',
    messagingSenderId: '1004613572381',
    projectId: 'repair-c9eba',
    authDomain: 'repair-c9eba.firebaseapp.com',
    storageBucket: 'repair-c9eba.appspot.com',
    measurementId: 'G-PK3CGC3JJ1',
  );

}