// File generated by FlutterFire CLI.
// ignore_for_file: type=lint


import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu4S8GB9NVVvFsFF7f8uRKWo4a8EJ-TQc',
    appId: '1:260631795016:web:76aa4fb36bb3b293c40f7d',
    messagingSenderId: '260631795016',
    projectId: 'repairtrack-bfd57',
    authDomain: 'repairtrack-bfd57.firebaseapp.com',
    storageBucket: 'repairtrack-bfd57.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAi-TIk_76VX9qsCoe4pH-vAvyK9VvJ3E',
    appId: '1:260631795016:android:587a8c7b4acb055ec40f7d',
    messagingSenderId: '260631795016',
    projectId: 'repairtrack-bfd57',
    storageBucket: 'repairtrack-bfd57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVl-3Ii0cuLWAhHgNP8DiJ8BfvEkmP-ZM',
    appId: '1:260631795016:ios:22ba96ed434a791fc40f7d',
    messagingSenderId: '260631795016',
    projectId: 'repairtrack-bfd57',
    storageBucket: 'repairtrack-bfd57.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVl-3Ii0cuLWAhHgNP8DiJ8BfvEkmP-ZM',
    appId: '1:260631795016:ios:22ba96ed434a791fc40f7d',
    messagingSenderId: '260631795016',
    projectId: 'repairtrack-bfd57',
    storageBucket: 'repairtrack-bfd57.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu4S8GB9NVVvFsFF7f8uRKWo4a8EJ-TQc',
    appId: '1:260631795016:web:efcbce899e7c6161c40f7d',
    messagingSenderId: '260631795016',
    projectId: 'repairtrack-bfd57',
    authDomain: 'repairtrack-bfd57.firebaseapp.com',
    storageBucket: 'repairtrack-bfd57.appspot.com',
  );
}
